version: '3.9'

services:

  ml-service:
    build: .

    container_name: ml-service

    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

    depends_on:
      - ml-service

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus